- name: Create worker join token
  delegate_to: ACon-0
  ansible.builtin.command: docker swarm join-token -q worker
  register: worker_join_token
  changed_when: worker_join_token | length > 0

- name: Check if swarm is enabled on node
  ansible.builtin.command: docker info --format {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: swarm_status

- name: Join Worker
  ansible.builtin.command: docker swarm join worker --token=""{{ worker_join_token.stdout }}
  when: swarm_status.stdout == 'inactive'
